name: C/C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ "main" ]

jobs:
  # each jobs (ie. build, test) run on separate VMs
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get install -f -y libcppunit-dev 
    - name: make
      working-directory: ./src
      run: make -f Makefile_linux.mk

    - name: Archive production artefacts  
      uses: actions/upload-artifact@v3
      with:
          name: testbasicmath-linux-bin
          path: src/testbasicmath

  test-linux:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:       
      # don't use checkout -> the workspace will be empty - uses: actions/checkout@v3  
      - name: install dependencies
        run: |
          sudo apt-get install -f -y libcppunit-dev 
      - name: Download testbasicmath-bin
        uses: actions/download-artifact@v3
        with:
          name: testbasicmath-linux-bin
          # downloaded artefact content is placed at the root of the workspace by default
      - name: run test
        shell: bash
        run: |
          ls -lsa
          chmod a+x testbasicmath
          ./testbasicmath
      # publish in Github UI
      - name: Publish Test Results 
        uses: EnricoMi/publish-unit-test-result-action@v2.3.0
        if: always()  # always run even if the previous step fails
        with:
          junit_files: "*Results.xml"
      - name: Archive unit test results  
        uses: actions/upload-artifact@v3
        if: always()  # always run even if the previous step fails
        with:
          name: unit-test-result
          path: cppTestBasicMathResults.xml
