name: C/C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get install -f -y libcppunit-dev 
#    - name: configure
#      run: ./configure
    - name: make
      working-directory: ./src
      run: make -f Makefile_linux.mk
    - name: simple run
      working-directory: ./src
      run: ./testbasicmath
      
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
